### ISSUE TITLE
Recent AutoMapper features aren't supported because I can't update AutoMapper beyond 3.1.1

### ISSUE THREAD

**Issue by enhendrickson** [razisyed/EntityUi#1]
While the titled issue is what prompted my submission, it's also worth noting that I can't run EntityUi at any higher version than 1.1.2.  If I do then DomainModelBase strangely disappears.  Any idea when you'll support an upgrade to AM 6.2 or any idea why I can't seem to get 1.1.13 to load?

**Comment by razisyed** [comment]
Thanks for the feedback, haven't had a chance to look at this yet
